wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.7.5
f:
  desc: null
  value: /home/andrew/.local/share/jupyter/runtime/kernel-d9fa4990-1d31-467e-aff3-43d246f594da.json
